[package]
description = "Library wrapping the awesome PokeAPI"
documentation = "https://github.com/mlemesle/rustemon/blob/main/README.md"
edition = "2021"
homepage = "https://github.com/mlemesle/rustemon"
keywords = ["pokeapi", "pokemon", "wrapper", "http", "rest"]
license-file = "LICENSE"
name = "rustemon"
readme = "README.md"
repository = "https://github.com/mlemesle/rustemon"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.29.0"
reqwest = {version = "0.11", features = ["blocking", "json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features= ["full"] }
