[package]
description = "Library wrapping the awesome PokeAPI"
documentation = "https://docs.rs/rustemon/latest/rustemon/"
edition = "2021"
homepage = "https://github.com/mlemesle/rustemon"
keywords = ["pokeapi", "pokemon", "wrapper", "http", "rest"]
license = "MIT"
name = "rustemon"
readme = "README.md"
repository = "https://github.com/mlemesle/rustemon"
version = "1.0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-cache-reqwest = "0.4.5"
log = "0.4.16"
reqwest = {version = "0.11.10", features = ["json"]}
reqwest-middleware = "0.1.6"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1.0"

[dev-dependencies]
tokio = {version = "1", features = ["full"]}
